notifications:
  email:
    recipients:
      - scott@tekuma.io
      - afika@tekuma.io
      - stephen@tekuma.io
    on_success: change
    on_failure: always


dist: trusty
sudo: true

services:
  - mysql

addons:
  apt:
    packages:
    - xvfb
    - nginx
    - chromium-chromedriver


language: node_js
node_js:
  - "6"

install:
  - export NODE_ENV=debug
  - npm install
  - ./get-testing-deps.sh
  - mysql -u root --host=127.0.0.1 --port=3306 -e 'CREATE DATABASE IF NOT EXISTS Tekuma_artworkdb'

before_script:
  - "export DISPLAY=:99.0"
  - "sh -e /etc/init.d/xvfb start"
  - sleep 3  # Recommendation from https://docs.travis-ci.com/user/gui-and-headless-browsers/

script:
  - java -version
  - /usr/lib/chromium-browser/chromedriver --version

  - export TEKUMA_TEST_DB=sqlite
  - npm run testserv
  - export TEKUMA_TEST_DB=mysql
  - cp ${TRAVIS_BUILD_DIR}/tests/ci-testdbconf.json ${TRAVIS_BUILD_DIR}/tests/testdbconf.json
  - npm run testserv

  # Patch Nightwatch configuration for Travis CI Ubuntu images
  - sed -i 's/\/usr\/lib\/chromium\/chromedriver/\/usr\/lib\/chromium-browser\/chromedriver/g' nightwatch.json

  # Search server should use the MySQL instance in this CI job
  - cp ${TRAVIS_BUILD_DIR}/tests/ci-testdbconf.json ${TRAVIS_BUILD_DIR}/serv/local-test-dbconf.json

  - node serv/manage.js info
  - node serv/manage.js clear

  - ./dev-spin.sh&
  - npm run testfront
