notifications:
  email:
    recipients:
      - scott@tekuma.io
      - afika@tekuma.io
      - stephen@tekuma.io
    on_success: change
    on_failure: always


dist: trusty
sudo: true

services:
  - mysql

addons:
  apt:
    packages:
    - xvfb
    - chromium-chromedriver


language: node_js
node_js:
  - "6"

install:
  - export NODE_ENV=debug
  - npm install
  - mysql -u root --host=127.0.0.1 --port=3306 -e 'CREATE DATABASE IF NOT EXISTS Tekuma_artworkdb'

script:
  - export TEKUMA_TEST_DB=sqlite
  - npm run testserv
  - export TEKUMA_TEST_DB=mysql
  - cp ${TRAVIS_BUILD_DIR}/tests/ci-testdbconf.json ${TRAVIS_BUILD_DIR}/tests/testdbconf.json
  - npm run testserv

  # Patch Nightwatch configuration for Travis CI Ubuntu images
  - sed -i s/\/usr\/lib\/chromium\/chromedriver/\/usr\/lib\/chromium-browser\/chromedriver/g nightwatch.json
