services:
  - mysql

language: node_js
node_js:
  - "6"

install:
  - export NODE_ENV=debug
  - export TEKUMA_TEST_DB=mysql
  - npm install

script:
  - cp ${TRAVIS_BUILD_DIR}/tests/ci-testdbconf.json ${TRAVIS_BUILD_DIR}/tests/testdbconf.json
  - npm run testserv
